"1":
  name: MOPSO
  title: MOPSO
"2":
  name: FPOMOPSO
  title: FPO-MOPSO
"3":
  name: SENIOR
  title: Senior Method
"4":
  name: MASTER_A
  title: Proposed Method A
"5":
  name: MASTER_B
  title: Proposed Method B
"6":
  name: MASTER_C
  title: Proposed Method C
