"0":
  name: "None"
  N_SIZE: 0
"1":
  name: Ring_5
  N_SIZE: 5
"2":
  name: Neumann
  N_SIZE: 5
"3":
  name: Cylinder
  N_SIZE: 5
"4":
  name: Hexagonal
  N_SIZE: 7
"5":
  name: Grid
  N_SIZE: 5
"6":
  name: Ring_3
  N_SIZE: 3
"7":
  name: Ring_7
  N_SIZE: 7
