"1":
  name: Rastrigin
  dimension: 10
  upper: 5.12
  lower: -5.12
"2":
  name: Ackley
  dimension: 10
  upper: 5.0
  lower: -5.0
"3":
  name: Griewank
  dimension: 10
  upper: 5.0
  lower: -5.0
"4":
  name: Sphere
  dimension: 10
  upper: 5.0
  lower: -5.0
"5":
  name: Booth
  dimension: 10
  upper: 10.0
  lower: -10.0
"6":
  name: Alpine
  dimension: 10
  upper: 10.0
  lower: -10.0
"7":
  name: ZDT6
  dimension: 10
  upper: 1.0
  lower: 0.0
"8":
  name: DTLZ1
  dimension: 7
  upper: 1.0
  lower: 0.0
"9":
  name: ZDT2
  dimension: 30
  upper: 1.0
  lower: 0.0
